spring.datasource.url=jdbc:mysql://localhost:3307/bank_management
spring.datasource.username=root
spring.datasource.password=9763883259
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect